spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    ROOT: INFO
    com.flab.hsw: TRACE
    org.springframework.context: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.web.filter: TRACE
    org.springframework.web.servlet: TRACE
